# Ultraviolet: terminal primitives and rendering structures.

require "./ultraviolet/geometry"
require "./ultraviolet/utils"
require "./ultraviolet/environ"
require "./ultraviolet/platform"
require "./ultraviolet/logger"
require "./ultraviolet/cancelreader"
require "./ultraviolet/cancelreader_windows"
require "./ultraviolet/style"
require "./ultraviolet/ansi_color"
require "./ultraviolet/cell"
require "./ultraviolet/buffer"
require "./ultraviolet/tty_state"
require "./ultraviolet/tty"
require "./ultraviolet/winsize"
require "./ultraviolet/winch"
require "./ultraviolet/poll"
require "./ultraviolet/poll_windows"
require "./ultraviolet/poll_bsd"
require "./ultraviolet/poll_linux"
require "./ultraviolet/screen"
require "./ultraviolet/screen_context"
require "./ultraviolet/layout"
require "./ultraviolet/border"
require "./ultraviolet/tabstop"
require "ansi"
require "./ultraviolet/key"
require "./ultraviolet/key_table"
require "./ultraviolet/mouse"
require "./ultraviolet/progress_bar"
require "./ultraviolet/event"
require "./ultraviolet/decoder"
require "./ultraviolet/styled"
require "./ultraviolet/uv_api"
require "./ultraviolet/console"
require "./ultraviolet/cursor"
require "./ultraviolet/window"
require "./ultraviolet/terminal"
require "./ultraviolet/terminal_screen"
require "./ultraviolet/terminal_reader"
require "./ultraviolet/terminal_reader_windows"
require "./ultraviolet/terminal_renderer"
require "./ultraviolet/terminal_unix"
require "./ultraviolet/terminal_windows"

module Ultraviolet
  VERSION = "0.1.0"
end
